#  From: https://github.com/boostorg/hana/blob/master/.travis.yml
#  and:  https://github.com/ldionne/dyno/blob/master/.travis.yml

language: cpp
dist: trusty
sudo: false

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/boost-1.64.0 # Keep this in sync with BOOST_VERSION

matrix:
  include:
    - env: COMPILER=g++-6
      addons: { apt: { packages: ["g++-6", "libzmq3-dev"], sources: ["ubuntu-toolchain-r-test"] } }

    - env: COMPILER=g++-7
      addons: { apt: { packages: ["g++-7", "libzmq3-dev"], sources: ["ubuntu-toolchain-r-test"] } }

    - env: COMPILER=clang++-3.8
      addons: { apt: { packages: ["clang-3.8", "lldb-3.8", "libzmq3-dev"], sources: ["llvm-toolchain-trusty-3.8", "ubuntu-toolchain-r-test"] } }

    - env: COMPILER=clang++-3.9
      addons: { apt: { packages: ["clang-3.9", "lldb-3.9", "libzmq3-dev"], sources: ["llvm-toolchain-trusty-3.9", "ubuntu-toolchain-r-test"] } }

    - env: COMPILER=clang++-4.0
      addons: { apt: { packages: ["clang-4.0", "lldb-4.0", "libzmq3-dev"], sources: ["llvm-toolchain-trusty-4.0", "ubuntu-toolchain-r-test"] } }

install:
  # Set the ${CXX} variable properly
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi
  - ${CXX} --version

  # Dependencies required by the CI are installed in ${TRAVIS_BUILD_DIR}/deps/
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}

  # Install a recent CMake
  - CMAKE_VERSION=3.8.0
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v${CMAKE_VERSION%.[0-9]}/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew install cmake || brew upgrade cmake
    fi
  - cmake --version

  # Install Boost headers
  - BOOST_VERSION=1.64.0 # Keep this in sync with the cached directory
  - BOOST_DIR=${DEPS_DIR}/boost-${BOOST_VERSION}
  - |
    if [[ -z "$(ls -A ${BOOST_DIR})" ]]; then
      BOOST_URL="http://sourceforge.net/projects/boost/files/boost/${BOOST_VERSION}/boost_${BOOST_VERSION//\./_}.tar.gz"
      mkdir -p ${BOOST_DIR}
      { travis_retry wget -O - ${BOOST_URL} | tar --strip-components=1 -xz -C ${BOOST_DIR}; } || exit 1
    fi

before_script:
  - cd "${TRAVIS_BUILD_DIR}"
  - (cd ${BOOST_DIR} && ./bootstrap.sh --with-libraries=program_options,filesystem && ./b2 cxxflags=-std=c++1y --with-program_options --with-filesystem)
  - (cd dependencies && ./install.sh)
  - (mkdir build && cd build && cmake .. -DBOOST_ROOT="${BOOST_DIR}" -DCMAKE_PREFIX_PATH="${TRAVIS_BUILD_DIR}/dependencies/install" -DCMAKE_INSTALL_PREFIX="${TRAVIS_BUILD_DIR}/build/install")

script:
  - cd ${TRAVIS_BUILD_DIR}/build
  - cmake --build . -- -j2
  - ctest -VV .
