# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

class MessageBody(object):
    NONE = 0
    RequestTraces = 1
    ReplyTraces = 2
    RequestStartInference = 3
    ReplyStartInference = 4
    RequestProposal = 5
    ReplyProposal = 6

